# Generated by Django 6.0.5 on 2026-06-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_tag_remove_book_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Genre',
        ),
    ]
