# Generated by Django 6.0.5 on 2026-06-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_options_book_bookfile_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_avatar',
            field=models.ImageField(default='', upload_to='books/books_avatars'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='bookFile',
            field=models.FileField(upload_to='books/books_texts'),
        ),
    ]
