# Generated by Django 6.0.5 on 2026-06-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_posted_by_alter_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='style',
        ),
        migrations.DeleteModel(
            name='BookStyle',
        ),
    ]
