# Generated by Django 6.0.5 on 2026-06-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_remove_book_style_delete_bookstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
