# Generated by Django 6.0.5 on 2026-06-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_book_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
