# Generated by Django 6.0.5 on 2026-06-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
