# Generated by Django 6.0.5 on 2026-06-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_remove_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_moderate_books', 'Can post and delete book')], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
