# Generated by Django 6.0.5 on 2026-06-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('books', '0015_remove_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourite_books',
            field=models.ManyToManyField(blank=True, related_name='favourite_books', to='books.book'),
        ),
    ]
